// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCle2EIt47960_96wr5eEA5yyKNJILYgWY',
    appId: '1:151405121879:web:5a78065a8e23a4c2932e12',
    messagingSenderId: '151405121879',
    projectId: 'hospital-app-c7ed8',
    authDomain: 'hospital-app-c7ed8.firebaseapp.com',
    storageBucket: 'hospital-app-c7ed8.firebasestorage.app',
    measurementId: 'G-H5F94K12S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAfgbjsclOFL-z8JWbQdI85hr42QNQd9Q',
    appId: '1:151405121879:android:54f827f4b05070e2932e12',
    messagingSenderId: '151405121879',
    projectId: 'hospital-app-c7ed8',
    storageBucket: 'hospital-app-c7ed8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKDqgU4JCZBdLno9i5R-r0I-w777Z-IQ',
    appId: '1:151405121879:ios:d1bbc571d52a715c932e12',
    messagingSenderId: '151405121879',
    projectId: 'hospital-app-c7ed8',
    storageBucket: 'hospital-app-c7ed8.firebasestorage.app',
    iosBundleId: 'com.example.hospitalproject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKDqgU4JCZBdLno9i5R-r0I-w777Z-IQ',
    appId: '1:151405121879:ios:d1bbc571d52a715c932e12',
    messagingSenderId: '151405121879',
    projectId: 'hospital-app-c7ed8',
    storageBucket: 'hospital-app-c7ed8.firebasestorage.app',
    iosBundleId: 'com.example.hospitalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCle2EIt47960_96wr5eEA5yyKNJILYgWY',
    appId: '1:151405121879:web:9b5b7178f0093e0e932e12',
    messagingSenderId: '151405121879',
    projectId: 'hospital-app-c7ed8',
    authDomain: 'hospital-app-c7ed8.firebaseapp.com',
    storageBucket: 'hospital-app-c7ed8.firebasestorage.app',
    measurementId: 'G-D8QDR7P0P0',
  );
}
